export const CartActionTypes = {
    'SET_ITEM_ADDED_TO_CART': 'SET_ITEM_ADDED_TO_CART',
    'ADD_ITEM_TO_CART': 'ADD_ITEM_TO_CART',
    'REMOVE_ITEM_FROM_CART': 'REMOVE_ITEM_FROM_CART',
    'INCREASE_ITEM_IN_CART': 'INCREASE_ITEM_IN_CART',
    'DECREASE_ITEM_FROM_CART': 'DECREASE_ITEM_FROM_CART',
    'CALCULATE_CART_SUBTOTAL_AMOUNT': 'CALCULATE_CART_SUBTOTAL_AMOUNT',
    'CALCULATE_CART_TOTAL_AMOUNT': 'CALCULATE_CART_TOTAL_AMOUNT',
    
}	