export const OrdersActionTypes = {
	'SET_ORDERS_TABLE_DATA': 'SET_ORDERS_TABLE_DATA',
	'UPDATE_ORDER_STATUS': 'UPDATE_ORDER_STATUS',
	'DELETE_ORDER': 'DELETE_ORDER',
	'SELECT_DATE_FILTER': 'SELECT_DATE_FILTER',		
}	